language: python

env:
  - HG_VERSION=2.6.1 BZR_VERSION=2.6b2
  - HG_VERSION=2.6.1 BZR_VERSION=2.5.1
  - HG_VERSION=2.6.1 BZR_VERSION=2.2.3
  - HG_VERSION=2.4 BZR_VERSION=2.5.1
  - HG_VERSION=2.2 BZR_VERSION=2.5.1
  - HG_VERSION=2.0 BZR_VERSION=2.5.1
  - HG_VERSION=1.9.3 BZR_VERSION=2.5.1

before_install:
  - pip install -q --use-mirrors Mercurial==$HG_VERSION
  - pip install -q --use-mirrors bzr==$BZR_VERSION
  - pip install -q --use-mirrors hg-git

script:
  - export GIT_TEST_OPTS='-v'
  - make
  - make -C contrib/remote-helpers
